### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by marzocchi** [Adven27/grpc-wiremock#1]
Hi there! Can you clarify the licensing of this project, possibly by adding a LICENSE file in the repository? Without it, nobody can use it or contribute to it.

For reference: https://choosealicense.com/no-permission/

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

**Comment by Adven27** [comment]
Hi! Thanks for pointing that out. Done.
