### ISSUE TITLE
Adding versions on docker hub

### ISSUE THREAD

**Issue by linouk23** [Adven27/grpc-wiremock#13]
### What
@Adven27 thanks for creating such an amazing project!

I've got a small request: could you please add tags to Docker Hub (i.e., currently there's only `latest` tag that I can pin for my tests and I guess it could cause weird issues later).

**Comment by linouk23** [comment]
Could you please also upload this version as [0.9](https://github.com/Adven27/grpc-wiremock/commit/71945fc60a593c59b7264f25fc35d63e014c3c19) or something? The tests started failing for me after gradle/protobuf versions were [updated](https://github.com/Adven27/grpc-wiremock/commit/e212b2b0839c427767656b8e01bd6d6c418200e2)  🤔

**Comment by Adven27** [comment]
@linouk23 try this [adven27/grpc-wiremock:0.0.9](https://hub.docker.com/layers/149422266/adven27/grpc-wiremock/0.0.9/images/sha256-264e72d7e77e60d5843b38852d5baa2a282ee937da7184f5f686ddab1237eed2?context=explore)
