### ISSUE TITLE
Allow to configure http and grpc ports

### ISSUE THREAD

**Issue by lcardito** [Adven27/grpc-wiremock#21]
Hey team!

Nice work on this one! A nice detail would be to allow the http and grpc ports to be configured from the env/command. The standard wiremock allows to override the command passing in the ports:

```
command: "--https-port 443 --port 9002"
```

Is this something we could look into?

Thanks!

**Comment by Adven27** [comment]
Hey! Thank you for the improvement request. I'll look at what we can do about it.

**Comment by Adven27** [comment]
Ports can be configured like this `-e GRPC_SERVER_PORT=5555 -e WIREMOCK_PORT=0`.
WireMock configuration options are described here https://github.com/Adven27/grpc-wiremock#2-configuring-wiremock-server
