### ISSUE TITLE
Suggestion: mention that you can precompile proto files for faster startup?

### ISSUE THREAD

**Issue by NielsUll** [Adven27/grpc-wiremock#4]
Hi!

We are using this for automated tests and would like it to start a bit faster.
I found out that doing my own image based on thismade it start a good deal faster, as long as I didn't update the .proto files:

    FROM adven27/grpc-wiremock
    # copy our own proto files
    COPY ./proto/*.proto /proto/
    # Start image faster by compiling everything when we build the image
    RUN gradle compileJava

    # copy wiremock mappings and files - could also be mounted
    COPY ./wiremock/mappings/* /wiremock/mappings/
    COPY ./wiremock/__files/* /wiremock/__files/

Perhaps this would be worth mentioning in the readme file?

**Comment by Adven27** [comment]
Hi! 
Great point: server generating is one of the most time-consuming parts indeed.
I'll update the readme with your advice.
