### ISSUE TITLE
How to increase thread/processes if testing under significant loads.

### ISSUE THREAD

**Issue by sp1rs** [Adven27/grpc-wiremock#6]
Hi, do I increase the performance of wiremock if testing under significant loads?
Is there any way to increase threads or processes?
Or any other configuration changes that can be done to improve the wiremock.

**Comment by Adven27** [comment]
I've added support for some perf related wiremock options and instruction how to use it in README.
For example you can use this property:
```docker run -e SPRING_PROFILES_ACTIVE=load adven27/grpc-wiremock```
